- squarelet/oidc/viewsets.py
This change creates a random `client_id` for all new clients, as opposed to just those that are confidential.
Currently, all clients created by `POST`ing to `/api/clients/` will have a `client_id` equal to an empty string; this will cause all but the first `POST` to fail, as `client_id` must be unique.
> Create client ID in all circumstances

- squarelet/organizations/serializers.py
- squarelet/organizations/tests/test_api.py
- squarelet/organizations/tests/test_querysets.py
This PR adds `id`s to the API responses for plans and subscriptions, as we discussed in our chat yesterday (the API overview discussion). I've added tests for these 4 (list/retrieve) endpoints as well to verify they return an id, and ran `inv format` on the code. The formatting made a whitespace change to the `test_querysets.py` which is the only reason why it's included here ✌️
> Added ID to plan and subscription API responses for PressPass

- squarelet/organizations/serializers.py
- squarelet/organizations/tests/test_api.py
This PR makes the subscriptions endpoint for the PP API allow expanding of `plan` data, and it includes a test for this feature. 
FYI @TylerFisher this allows our "Manage Organization" page to properly render the "SubscriptionCard" with the plan's title.
> PP Subscriptions endpoint can expand plan data

- squarelet/organizations/serializers.py
- squarelet/organizations/tests/test_api.py
This PR adds FlexFields to the PressPassNestedInvitationSerializer to allow expanding user data on demand. This change addresses a need we have in our frontend: to enable organization admins to manage requests to join, we need the username and/or email for these requests to make sense. To avoid making `n` API requests to retrieve each user's data, this seemed like a better solution.
I've added a test for the expanded nested invitation endpoint.
> Expandable user data on presspass nested invitations

- squarelet/oidc/rules.py
- squarelet/oidc/tests/factories.py
- squarelet/oidc/tests/test_api.py
- squarelet/oidc/viewsets.py
This PR changes who can access the `/pp-api/clients` endpoints in the API, restricting access to admins only. I've updated the tests to reflect this in general, and I've also added an additional test for each endpoint.
> Limit clients api to admin-only users

- .vscode/tasks.json
- README.md
- config/settings/base.py
- local.yml
This PR clarifies a few things in the readme and also adds a [tasks.json](https://code.visualstudio.com/Docs/editor/tasks), which I'm still testing, that enables you to run all the docker-compose sessions for DocumentCloud at once using `Cmd-Shift-B` or `Ctrl-Shift-B` (win/linux) in VS Code and probably Github Codingspaces.
> Readme install

- compose/local/nginx/nginx.conf
This change was necessary to get the websockets used by Big Local News' React frontend to work via Squarelet's NGINX instance.
> Move websockets instructions in nginx config

- squarelet/static/assets/biglocalnews.svg
This is necessary for the logo to work on computers that don't have the custom font installed.
> Convert font in BLN logo to a path

- squarelet/core/models.py
- squarelet/core/views.py
- squarelet/templates/core/component/alerts.html
- squarelet/templates/core/erh_landing.html
- squarelet/templates/core/erh_resource.html
This adds a new table, Alerts, with configurable messages. By checking each view in the table, we can get a list of messages to display for each user segment ("Logged In", "Hub Eligible", "Logged Out").
Alerts are rendered in the header of both the landing page and resource page templates. When there is only one alert, it's rendered as a paragraph of text. When there are multiple, they are rendered as a list of paragraphs.
> Displays alert messages on landing and resource pages

- squarelet/core/templatetags/markdown.py
This allows linebreaks to be rendered when parsing Markdown content.
> Whitelist the <br /> tag

- squarelet/core/views.py
This updates the category display to only include resources that have:
1. a Status of "Available", and
2. a Show? of "Ready"
This updates resource pages and search results to present only resources that have:
1. a Status of "Available", and
2. a Show? of "Ready" or "Kondo"
> Fix resource visibility

- requirements/local.txt
Updates the pip-tools version.  Doing an `inv build` should allow the `inv pip-compile` command to run successfully.
> update pip-tools.  closes #221

- README.md
This is just a simple onboarding edit that may help people avoid making the mistake I made.
> Remove period to avoid copying it accidentally.

- .gitignore
- requirements/local.in
- requirements/local.txt
- tasks.py
This adds `pip-audit` as a local dependency so we can better prioritize package upgrades to address known vulnerabilities.
Here is the output from the initial run:
```sh
Name                          Version   ID                  Fix Versions
----------------------------- --------- ------------------- -------------------
certifi                       2018.4.16 PYSEC-2022-42986    2022.12.7
certifi                       2018.4.16 PYSEC-2023-135      2023.7.22
cryptography                  3.4.8     PYSEC-2023-254      41.0.6
cryptography                  3.4.8     GHSA-w7pp-m8wf-vj6r 39.0.1
cryptography                  3.4.8     GHSA-x4qr-2fvf-3mr5 39.0.1
cryptography                  3.4.8     GHSA-5cpq-8wj7-hf2v 41.0.0
cryptography                  3.4.8     GHSA-jm77-qphf-c4w8 41.0.3 …
```
> Adds `pip-audit` package and task

- app.json
- postdeploy.sh
Closes #225 
This updates our Heroku Pipeline, running a `postdeploy` script that copies the staging database into the review app's database. This should only run when `HEROKU_APP_NAME` env var is present, which should only be in the context of a review app.
This allows us to deploy review apps that contain migrations, without messing up the schema of the staging database.
> Clone staging database into review apps

- app.json
The `standard-1x` config for a basic worker dyno product produced to the recurring error messages:
```
2025-02-08T02:06:49.183597+00:00 heroku[worker.1]: Process running mem=609M(118.2%)
2025-02-08T02:06:49.185821+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
```
At 2x, the worker dyno stops producing this error.
> Double worker memory for review apps

- compose/production/django/entrypoint
Currently, if a connection to the PostgreSQL database cannot be
established, operators are instructed to wait indefinitely. They need to
exercise their own judgement to determine that an unrecoverable error
may have occurred, and they must then formulate their own plan to
diagnose the problem. This change introduces a suggestion about the
possibility of failure and some contextual information that will assist
in debugging. It also causes the script to fail immediately for truly
exceptional circumstances such as the absence of required modules.
---
I've also submitted this patch to the "template" project from which the script originated: https://github.com/cookiecutter/cookiecutter-django/pull/3782
As noted there, I've arbitrarily chosen 30 seconds as the duration to wait before suggesting …
> Provide more context when starting PostgreSQL

- .github/workflows/test.yml
Closes #234 
Because of branch protection rules, checks on this commit need to pass before I can cleanly merge into `master`. In addition to changes here:
1. I've disabled Codeship from building on pushes to `master`. The final branch it builds on is `dev`.
2. I've updated Heroku to add the `squarelet` app as a production app in our `squarelet-pipeline`. It will automatically deploy whenever `master` is updated with commits passing any required checks set up in GitHub.
The `dev` branch doesn't interact with Heroku pipelines at all.
> Update CI GitHub Action to run on pushes to the master branch

- squarelet/organizations/models/payment.py
There was a bug where if you cancelled your subscription, than resubscribed before your current subscription lapsed at the end of the billing period, it would get marked as cancelled in our database and be out of sync with stripe.
> fix bug when modifying cancelled subscription

- frontend/css/main.css
- squarelet/core/templatetags/handleintent.py
- squarelet/templates/account/login.html
- squarelet/templates/account/signup.html
- squarelet/templates/core/component/navigation.html
- squarelet/templates/templatetags/sign_up_message.html
- squarelet/users/forms.py
- squarelet/users/tests/test_forms.py
Closes #248 
Updates Sign Up page to bring the design inline with the new login page.
Now after signup, the user will enter the onboarding flow because the `post_login` function is called during signup. At a minimum, the user will see a nice message asking them to confirm their email address before continuing on.
This removes the Stripe fields from `SignupForm` but leaves the hidden `plan` field in place. If `plan` has a value when saving the form, the Plan slug is added to session storage for use during the onboarding flow. See #267 for more.
- Fixes a bug where the "Signup" navigation link would create incorrect URL params.
> Updates Sign Up page

- squarelet/templates/account/onboarding/mfa_setup.html
- squarelet/users/adapters.py
- squarelet/users/admin.py
- squarelet/users/views.py
Closes #302 
Closes #303 
This improves our 2FA opt-in during onboarding by:
1. Checking for any unverified emails on the user's account; if they exist, the form will not be accepted by `allauth`'s standard rules.
2. Allowing users to skip submitting the code during the "opt-in" step.
3. Setting the `last_mfa_date` when users skip during the "opt-in" step.
4. Showing the `last_mfa_data` field in the User model's admin interface.
> Fixes for 2FA opt-in

- frontend/css/main.css
- squarelet/templates/account/login.html
- squarelet/templates/account/signup.html
- squarelet/templates/templatetags/services_list.html
- Services list now adapts to the height of the login/signup step it's presented alongside. This will enable overflow scrolling on most pages when we have a longer list of services.
- Services now link out when they have a `base_url`.
- Typography and layout refinements.
- **[Sign Up](https://squarelet-pi-allanlasse-qqivzh.herokuapp.com/accounts/signup/?intent=squarelet)**: note how the services list is shorter than the page's form
- **[Sign In](https://squarelet-pi-allanlasse-qqivzh.herokuapp.com/accounts/login/?intent=documentcloud)**: note how the services list is longer than the page's form
1. Should services link to their `base_url` or their sign-in intent?
> Polish services list styling

- frontend/autocomplete.ts
- squarelet/templates/organizations/organization_list.html
Fixes #298
Updates `autocomplete.ts` and `autocomplete.css` to fix how flex layout is applied to organization search results.
> Update formatting on organization search results

- squarelet/core/templatetags/pass_query.py
- squarelet/core/templatetags/tests/test_pass_query.py
- squarelet/templates/account/login.html
- squarelet/templates/account/signup.html
- squarelet/templates/core/component/navigation.html
- squarelet/users/templatetags/pass_query.py
Closes #297
Adds a new `pass_query` template tag for improved control over persisting querystrings between routes.
Removes setting next URL param to the current route in templates, fixes `/selectplan/` forwarding after logging in from the homepage.
> Fixes query parameters for sign up and sign in links

- squarelet/organizations/models/organization.py
- squarelet/organizations/tests/test_models.py
Fix a bug where the stripe token is used twice, which will throw an error
> fix stripe token double use

- config/settings/base.py
- squarelet/templates/account/signup.html
- squarelet/users/forms.py
- squarelet/users/tests/test_forms.py
Closes #309 
This is actually removing one of our password validators, so we should decide if this is what we want. Alternately, we can make it check against the full name field.
The TOS field is only on the signup form. We don't store anything, but anyone who creates an account will have to check the box that they agree to it.
> Add TOS check, tighten similarity check

- squarelet/users/forms.py
- squarelet/users/tests/test_forms.py
- squarelet/users/views.py
When creating an organization subscription fails, the user gets a 500 error. This handles the situation when saving the premium form, and 
1. Try subscribing to a premium plan [using a test card that will be declined](https://docs.stripe.com/testing?testing-method=card-numbers#declined-payments).
2. Check that the page reloads with an error message on the form.
3. Try creating a new organization and submitting the form with a declined card. The organization should be created even if the form fails to save, and then it should be available in the organization selection when rerendered.
4. Make sure the subscription still works when using a working card (`4242 4242 4242 4242`)
> Handle subscription errors in `PremiumSubscriptionForm`

- squarelet/templates/organizations/invitation_detail.html
Closes #328 
- Uses fresh buttons and correctly render "reject" button with caution styling
- Uses `next` param for sign in and sign up links, redirecting users back to their invitation after creating an account
- Updates language on invitation page
1. Create an organization
2. Invite an email address to join (easiest if you use `<youremail>+invitation-test@muckrock.com`)
3. Log out
4. Click the link in the invitation email
5. Sign up for a new account, get redirected back to the invitation
6. Accept or reject the invitation
> Update invitation detail template

- compose/local/django/start
- config/settings/base.py
- requirements/base.txt
- requirements/local.txt
- requirements/production.txt
- squarelet/templates/account/signup.html
- squarelet/users/adapters.py
- squarelet/users/forms.py
- squarelet/users/views.py
Instead of automatically creating an account on social login, this confirms with the user if they want to log in to an existing account or create a new one.
@allanlasser - This probably needs some design tweaks
I used the copy supplied by @amandabee , but it can be further edited if needed
To test, attempt to use the social login with an email address that is not associated with an account.
https://squarelet-pi-social-log-dmdlac.herokuapp.com/accounts/login/
> Social login flag

- squarelet/organizations/filters.py
- squarelet/organizations/models/organization.py
- squarelet/organizations/serializers.py
- squarelet/organizations/viewsets.py
Third-party clients want to be able to filter the list of organizations by subtype, so that they can better classify verified organizations using their service.
Related to #377 
1. Sign into the preview deployment
2. Go to `/api/organizations`
3. Try filtering by subtype
> Adds filterable list of subtypes to organization list results

- squarelet/templates/account/email/email_confirmation_signup_message.html
- squarelet/templates/account/onboarding/confirm_email.html
- squarelet/templates/account/onboarding/mfa_opt_in.html
- squarelet/templates/account/onboarding/mfa_setup.html
- squarelet/templates/account/onboarding/verification.html
- squarelet/templates/mfa/authenticate.html
- squarelet/templates/organizations/your_organizations.html
- squarelet/templates/pages/selectplan.html
- squarelet/templates/templatetags/sign_up_message.html
- squarelet/templates/users/user_detail.html
- squarelet/templates/users/user_form.html
This should get everything in #389 but it's possible I missed some. I normalized links so `target="_blank" rel="noopener norefferer"` is the first attribute, just so it's easier to check.
> Help and airtable links open in new tabs

- squarelet/core/tests/test_utils.py
- squarelet/core/utils.py
Fixes #398
- Escapes from `mailchimp_subscribe` and `mailchimp_journey` functions when missing an API key or in a dev environment
- Overrides these settings when testing with `TestMailchimpJourney`
> Avoid starting Mailchimp journeys outside production environments

- config/urls.py
- squarelet/oidc/views.py
This enables MuckRock staging review apps to add their URIs on squarelet staging with an admin account. 
Should be able to go to the web from for one of your local clients and do a POST with a payload like this
{
"action": "add",
"redirect_uris": [
"https://example.com",
]
}
> Adds API endpoint on staging/dev environment to add redirect URIs

- squarelet/organizations/models/payment.py
- squarelet/organizations/tasks.py
Fixes #388
- Formats the message using Slack's block syntax and links
- Adds organization avatar to decorate the message for easier visual identification
- Provides additional before/after detail when a plan is modified
I've updated the Org and Pro plans in the deploy preview to send webhook updates to our `#notify-premium` channel. Starting, modifying, and cancelling a personal or group org subscription should dispatch a Slack message.
> Enhance formatting of Slack messages

- squarelet/users/adapters.py
- squarelet/users/tests/test_adapters.py
We bridged the onboarding logic during development in the `post_login`, but never undid the bridge. This may explain some strange login behavior, like in #400.
> Fix onboarding check in `user.post_login`

- .gitignore
- squarelet/core/tests/test_utils.py
- squarelet/organizations/fe_api/test_viewsets.py
- squarelet/organizations/querysets.py
- squarelet/organizations/tests/factories.py
- squarelet/organizations/tests/test_models.py
- squarelet/organizations/tests/test_querysets.py
Fixes #322
- Adds conditions to the `OrganizationQuerySet.get_viewable` method to only return organizations that have been verified or have exisiting charges.
- Adds test coverage for `OrganizationQuerySet`.
> Limits visible organizations

- squarelet/templates/account/reauthenticate.html
If a user puts in the wrong password in the reauthentication page, they don't get any feedback that this happened! This displays the errors on the page as expected.
> Display errors on reauthentication page

- squarelet/templates/users/user_form.html
- squarelet/templates/widgets/avatar.html
A few of the buttons were missing a primary styling, so they fell back to our default gray color. This fixes the color of the buttons.
> Fix button colors in `user_form.html`

- squarelet/templates/organizations/organization_list.html
- squarelet/templates/organizations/your_organizations.html
- squarelet/templates/users/user_detail.html
- squarelet/users/views.py
Discovered these issues while working on #444. They're unrelated, so opened a new PR for them.
- On the `/organizations/` page, invitations to orgs were duplicated in the left and right columns. This deduplicates invitations in the `organization_list` view by adding a flag to show invitations in the `your_organizations.html` fragment.
- Pending requests to join an organization were missing from the `your_organizations.html` fragment and the `UserDetailView` context.
- Fix button styling on invitation actions on the `/organizations/` route.
> Fixes bugs in organization list
