MuckRock/squarelet

- compose/local/nginx/nginx.conf
Add minimal config to pass along websocket requests
> Change nginx to enable dev-mode websockets to work

- squarelet/statistics/admin.py
- squarelet/templates/organizations/email/receipt.html
Purely written content change, no code changes. Should fix #95
> Edited professional and organizational upgrade email templates

- frontend/scroll-controller.ts
> Update arrow disabled state when window resizes

- config/urls.py
- frontend/css/erh.css
- squarelet/core/views.py
- squarelet/templates/core/component/erh/logged-out-copy.html
- squarelet/templates/core/erh_about.html
- squarelet/templates/core/erh_landing.html
- squarelet/templates/core/erh_resource.html
> Adds about page that includes landing-page language

- squarelet/core/templatetags/handleintent.py
- squarelet/templates/core/component/services.html
> Add KEH to services lists

- squarelet/templates/core/component/navigation.html
- squarelet/templates/core/erh_landing.html
- squarelet/templates/core/erh_resource.html
> Redirect on sign in/up

- squarelet/templates/base.html
- squarelet/templates/core/erh_about.html
- squarelet/templates/core/erh_landing.html
- squarelet/templates/core/erh_resource.html
> Enhance sharing preview metadata

- config/settings/base.py
- initialize_dotenvs.py
- squarelet/core/context_processors.py
- squarelet/core/utils.py
- squarelet/organizations/views.py
- squarelet/templates/base.html
- squarelet/users/forms.py
Fixes #161
Not required for KEH 1.2 release
Should we replace the Mixpanel event tracking with any other event tracking?
> Remove Mixpanel

- squarelet/templates/core/erh_landing.html
> Change label text for gated resources

- squarelet/templates/core/erh_landing.html
> Display category page name when on category search result page

- squarelet/core/views.py
> Sort and filter list of searchable providers

- frontend/css/erh.css
- squarelet/core/models.py
- squarelet/core/views.py
- squarelet/templates/core/erh_resource.html
> Disable access button for expired resources

- config/settings/local.py
- config/settings/production.py
- config/urls.py
- frontend/css/erh.css
- squarelet/core/models.py
- squarelet/core/views.py
- squarelet/templates/core/component/newsletter.html
- squarelet/templates/core/erh_landing.html
This adds a newsletter popup that appears for all users until it is submitted or declined. The component will record a submission or declination to `localStorage`, and as long as a value exists will not appear again.
> Newsletter popup for all users

- README.md
- compose/local/vite.Dockerfile
- local.yml
- vite.config.ts
Closes #184
I ran through a fresh start, fixing errors where they popped up and adding additional context to the README. 
There were a few configuration issues with our Vite container, so I cleaned those up. It should install correctly, without requiring a local Node installation.
> Fix Vite issues with Docker, update README

- local.yml
- squarelet/templates/account/email/email_confirmation_signup_message.html
There are some merge conflicts from master (which revise_welcome_message is based on). This is the only file I've actually edited:
https://github.com/MuckRock/squarelet/blob/b8dca5c213f9b4a6fac52c58a12486ea7a19e651/squarelet/templates/account/email/email_confirmation_signup_message.html
> Revise welcome message

- squarelet/fixtures/services.json
- squarelet/services/tests/test_models.py
Small fix to prevent tests from failing when reusing the database.
> Fixes tests, adds fixtures for Services models

- frontend/css/main.css
- squarelet/templates/base.html
- squarelet/templates/footer.html
It's as close as I could get to the MuckRock footer..The current squarelet footer is broken on some mobile devices at full zoom, and this one is too. I tried fixing it, but still could use work.. Closes #242
> Updated footer

- squarelet/organizations/forms.py
> Adds list of domains under form option, let's users know how to add them. 

- README.md
- config/settings/base.py
- config/settings/production.py
- docs/deploy.rst
- squarelet/core/mail.py
- tasks.py
Closes #299 
We were setting `SQUARELET_URL` to `squarelet-staging.herokuapp.com` on Heroku, so this sets it programmatically in settings.
> Set SQUARELET_URL based on HEROKU_APP

- squarelet/organizations/models/organization.py
Will open a new issue to display the requests to join elsewhere
> Filters for invites that were sent to the user by adding request=False

- config/settings/base.py
- squarelet/templates/account/login.html
Put social login behind a feature flag for now
> Social login flag

- squarelet/core/utils.py
Update the mailchimp journey for DocumentCloud
> update documentcloud mailchimp journey

- frontend/css/user_detail.css
- squarelet/templates/users/user_detail.html
- squarelet/users/views.py
Fixes #395
Clarifies our language around verification and de-emphasizes individual verification.
Sign in to each of our testing user profiles for staging ("Staging Unverified User", "Staging verified independent journalist also a member of a verified org", "Staging member of verified org", "Staging Verified Independent Journalist") and check that it's clear where your verified status comes from.
> Fixes for Verification section

- squarelet/core/utils.py
- squarelet/organizations/models/payment.py
> Added mailchimp journeys for verified and unverified orgs who upgrade

- frontend/css/user_detail.css
- squarelet/templates/organizations/organization_list.html
- squarelet/templates/organizations/your_organizations.html
- squarelet/templates/pages/selectplan.html
- squarelet/templates/users/user_detail.html
- squarelet/users/views.py
Closes #394
- Provides detail about the Premium plan benefits to free users
- Provides detail about the Premium plan benefits to subscribed users
- Provides a link to view all plans we offer (`/selectplan/` route)
> Enhances the Plan section

- squarelet/templates/organizations/your_organizations.html
> Allow org members request verification
